### Test GET request
GET http://localhost:300/api/
Content-Type: application/json

### Test POST request
POST http://localhost:3000/api/test
Content-Type: application/json

{
    "key": "value"
}

### Test PUT request
PUT http://localhost:3000/api/test/1
Content-Type: application/json

{
    "key": "newValue"
}

### Test DELETE request
DELETE http://localhost:3000/api/test/1
Content-Type: application/json


### Register
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "email": "tormit68@gmail.com",
    "password": "123456789",
    "name": "Mitchel Torres",
    "first_name": "Mitchel",
    "last_name": "Torres",
    "telephone": "123454789",
     "role": "admin"
}



### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "tormit68@gmail.com",
    "password": "123456789"
}

### Category
POST http://localhost:3001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Ramos",
    "description": "Categoría para ramos de flores"
}

### Get all categories
GET http://localhost:3001/category
Content-Type: application/json

### Create category
POST http://localhost:3001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Eventos",
    "description": "Categoría para eventos"
}

### Update category
PUT http://localhost:3001/category/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Eventos Actualizados",
    "description": "Nueva descripción"
}

### Delete category
DELETE http://localhost:3001/category/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg


### Get all subcategories
GET http://localhost:3001/subcategory
Content-Type: application/json

### Create subcategory
POST http://localhost:3001/subcategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Graduación",
    "image": "https://localhost:3001/uploads/brand/graduation.svg",
    "category_id": "266c0c13-568d-4bba-8f91-048bffad000f"
}

### Get subcategories by category
GET http://localhost:3001/subcategory/category/:categoryId
Content-Type: application/json

### Update subcategory
PUT http://localhost:3001/subcategory/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Bodas Actualizadas",
    "image": "https://example.com/new-image.jpg",
    "category_id": "category_uuid_here"
}

### Delete subcategory
DELETE http://localhost:3001/subcategory/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg
### Create Categor

POST http://localhost:3001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Eventos",
    "description": "Categoría para eventos"
}

### Create Subcategory
POST http://localhost:3001/subcategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Bodas",
    "image": "https://example.com/bodas.jpg",
    "category_id": "b754ddf8-e150-4168-9be6-ef17c0cab1cb"
}


### Get all products
GET http://localhost:3001/product
Content-Type: application/json


### Get all subcategories
GET http://localhost:3001/subcategory
Content-Type: application/json

### Create product
POST http://localhost:3001/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "name": "Bienvenido Graduado",
    "description": "Ramo de flores para graduación",
    "SKU": "RF004",
    "price": 11.99,
    "category_id": "b754ddf8-e150-4168-9be6-ef17c0cab1cb",
    "subcategory_id": "ece03e65-4ca6-47cb-9252-a36c0fbf008b"
}


### Get all inventory
GET http://localhost:3001/inventory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg
### Create inventor
POST http://localhost:3001/inventory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "quantity": 6119,
    "product_id": "26fa57c9-d3c5-4606-b417-126348c37052"
}

### Get all products
GET http://localhost:3001/product
Content-Type: application/json

### Update inventory
PUT http://localhost:3001/inventory/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "quantity": 150
}

### Update inventory
PUT http://localhost:3001/inventory/f9ab9394-def4-413f-9f45-649c53c0adca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "product_id": "f9ab9394-def4-413f-9f45-649c53c0adca",
    "quantity": 150
}

### Delete inventory
DELETE http://localhost:3001/inventory/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg


### Get all products
GET http://localhost:3001/product
Content-Type: application/json

### Create product image
POST http://localhost:3001/product-images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "image_url": "http://localhost:3001/uploads/products/valentin_hjg.png",
    "product_id": "26fa57c9-d3c5-4606-b417-126348c37052"
}

### Get product images
GET http://localhost:3001/product-images/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg


### Create product images in bulk
POST http://localhost:3001/product-images/bulk
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOTkxODUzZC02OTZmLTQzMWEtODYyNC1hODRhMGEwYzQzMjAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAwNjYwODEsImV4cCI6MTc0MDE1MjQ4MX0.2IANm8uYqePEbmZ3DjjSdvU4Sl90YsE8XLowejwjWCg

{
    "product_id": "uuid-of-product",
    "images": [
        {
            "image_url": "https://example.com/images/product1-front.jpg"
        },
        {
            "image_url": "https://example.com/images/product1-back.jpg"
        },
        {
            "image_url": "https://example.com/images/product1-side.jpg"
        }
    ]
}
#####
GET http://localhost:3001/order-details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZmVjNmIxMi02NzRhLTQxZDUtODQyMi03ZTlmZDJlMDU3MDUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4MTI5NTcsImV4cCI6MTczOTg5OTM1N30._ropTO3r5EmhoaV-5Abf4mpFeQGHGFNZw_2QW_VJXd8